### ISSUE TITLE
Repair issue with chart ppt : Sample_05_Chart.php

### ISSUE THREAD

**Issue by amitrajput92** [PHPOffice/PHPPresentation#353]
Hi,

I have used this library for creating pptx presentation. Everything working fine except charts ppt.
when i created chart ppt and open in office 2017 and mac it shows me repair option. After repair charts are not shown in ppt. I used latest version 0.8.0 version of dev branch. Attached chart file. Please have
[Sample_05_Chart(1).pptx](https://github.com/PHPOffice/PHPPresentation/files/929573/Sample_05_Chart.1.pptx)
 look into this.

**Comment by larryb-redflare** [comment]
Using XML Package Validator the problem with charts is

The 'val' attribute is invalid - The value '100.00%' is invalid according to its datatype 'http://schemas.openxmlformats.org/drawingml/2006/main:ST_PositiveFixedPercentage' - The string '100.00%' is not a valid Int32 value.

This is caused by line 102 in PhpPresentation\Writer\PowerPoint2007\PptCharts Line 102

      $objWriter->writeElementIf($hPercent != null, 'c:hPercent', 'val', $hPercent . '%');

changing this line to (dropping the % character to allow it to be a number)

      $objWriter->writeElementIf($hPercent != null, 'c:hPercent', 'val', $hPercent );

means MS Powerpoint 2016 opens the files without insisting on a repair and without stripping the charts when repaired.

**Comment by dlollman** [comment]
I am still having this issue even when changing line 102 (on master branch). Any other things I can do? I verified that the c:hPercent val is "100" and not "100%".

I have tried other branches as well (develop, etc) to no avail.

Thanks all.

**Comment by phpsb** [comment]
hi this issue are you solve?
i meet same issue.
@dlollman

**Comment by phpsb** [comment]
this issue how to solve ?

i use dev-master branch and edit PptCharts Line 102

but, to no avail.

anybody help me ?

@amitrajput92 @larryb-redflare

**Comment by Progi1984** [comment]
@phpsb @dlollman @amitrajput92 @larryb-redflare Duplicates #382.
