### ISSUE TITLE
Animation writing off by one

### ISSUE THREAD

**Issue by williammck** [PHPOffice/PHPPresentation#446]
When using the PowerPoint2007 Writer, all the slide animations are off by one. For example, the first shape I animate has no animation, all the rest do, and the next shape I insert has an animation, even though I did not animate it.

I've traced it back to issue #227 and PR #229.
I'm not exactly sure why that would be causing the issue, as that commit was designed to fix a similar bug, but would something have changed in the meantime to where the slide is no longer at ID 1?

**Comment by Aggiekev** [comment]
I FINALLY figured this one out. 

The issue #227 solved one aspect of the problem but there is still an issue with how the shapes are added to the Slide itself. The writeShapeCollection function in AbstractSlide.php starts the shapeId at 0 instead of 1. Since the Slide is position 0, it ends up putting the first Shape added to the Slide at the end of the array of components. That is why the animation is one off.

To fix this, the function needs to have the default value for shapeId be set to 1 instead of 0.

`protected function writeShapeCollection(XMLWriter $objWriter, $shapes = array(), &$shapeId = 1)`
